FROM hasura/graphql-engine:v2.7.0
EXPOSE 8080
ENV HASURA_GRAPHQL_DATABASE_URL='postgres://postgres:mySecret@pdelprat-postgres.dp-tuto.com:5432/postgres'
ENV HASURA_GRAPHQL_ENABLE_CONSOLE="true"
ENV HASURA_GRAPHQL_ADMIN_SECRET=aooQD*G&mF66nFqV 
